### PR TITLE
Application name changed

### PR DESCRIPTION
**Pull request by KIchiyanagi**
app name is changed: Works Mobile -> LINE WORKS

### CODE REVIEW

**Comment by gosali** [comment]
Hi @KIchiyanagi , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @KIchiyanagi , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by Clarare** [comment]
Hi @KIchiyanagi , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by Clarare** [comment]
@KIchiyanagi >: Thank you for your feedback and suggestion! 

The feedback is considered. We will tune part of  your feedbacks in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
		
Microsoft C&E Localization Team

**Pull request merged**
