### PR TITLE
High performance is missing from the table

### PR DESCRIPTION
**Pull request by nnasaki**
quick fix.

### CODE REVIEW

**Comment by gosali** [comment]
Hi @nnasaki, we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by nnasaki** [comment]
@gosali Thank you for review. However, I can not understand that it takes too much time for such simple corrections. Is it a problem that the difference other than "High Performance" which is the correction part is displayed? If so, I apologize. I edited it on Github and it did.

**Comment by kanreisa** [comment]
👍 +1

**Comment by gosali** [comment]
@nnasaki , Thank you for your feedback and suggestion! 
		
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
		
Microsoft C&E Localization Team

**Pull request merged**
